errbit:
  image: errbit/errbit:latest
  ports:
    - "8080:8080"
  links:
    - mongo
  environment:
    - PORT=8080
    - RACK_ENV=production
    - MONGO_URL=mongodb://mongo:27017/errbit
#    - DB_BS=1
mongo:
  image: mongo:3.0
  ports:
    - "27017"
  command: -smallfiles

